name       : libgestures
version    : 2.0.1
release    : 1
source     :
    - https://github.com/hugegreenbug/libgestures/archive/v2.0.1.tar.gz : 739c4e80a585e8a1b907702d8135357c6ec7f16fcc75b9e0b48fc22b0bd9a56b
license    : BSD-3-Clause
summary    : ChromiumOS libgestures ported to Linux
description: |
    ChromiumOS libgestures ported to Linux
clang      : no
setup      : |
    ./apply_patches.sh
build      : |
    %make
install    : |
    %make_install
